// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package generex.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mifmif.common.regex.Generex;

public class RandomStringWithPattern extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Pattern;

	public RandomStringWithPattern(IContext context, java.lang.String Pattern)
	{
		super(context);
		this.Pattern = Pattern;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Generex generex = new Generex(this.Pattern);

		// Generate random String
		String randomStr = generex.random();

		return randomStr;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RandomStringWithPattern";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
