// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("9d0ecaa0-c99d-43ea-8f7c-bcde897ba53c"),
	Geocodio("4fa9c2d9-942b-43b1-a2f3-b9485c83d9c1"),
	LocationIQ("1dca48ec-8f11-4bdf-b8d1-0788d2c785c3"),
	MapQuest("c69145ef-4444-4cd6-9ed8-987e4974d2b0");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
