// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("17030af4-f65b-4ff1-96a1-c996888b555f"),
	low("dd93e427-413b-49a5-8362-0fcf6b60c764"),
	medium("ec9790ca-0646-4fcc-bd02-21ca7e4579ec"),
	high("5121626c-1a17-4ff5-9815-1df61086e9a9"),
	custom("6ca91a60-1d64-4c84-afc7-eb8436180578");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
