// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Enumeration_Example
{
	Example_1("d6837aec-8d3b-450f-b7ce-235149b4a10e"),
	Example_2("79a4c61a-029c-4ba6-96dc-cd62e0bee3e7");

	private final java.lang.String i18nCaptionKey;
	
	private Enumeration_Example(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
