// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GenerateBuilder(
		myfirstmodule.proxies.Test _test
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Generate");
		builder = builder.withParam("Test", _test);
		return builder;
	}

	public static void aCT_Generate(
		IContext context,
		myfirstmodule.proxies.Test _test
	)
	{
		aCT_GenerateBuilder(
				_test
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Test");
		return builder;
	}

	public static myfirstmodule.proxies.Test dS_Test(IContext context)
	{
		Object result = dS_TestBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Test.initialize(context, (IMendixObject) result);
	}
}
