// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Test implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Test";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Pattern("Pattern"),
		RandomString("RandomString");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Test(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Test(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testMendixObject)
	{
		if (testMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!testMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testMendixObject = testMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Test initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Test(context, mendixObject);
	}

	public static myfirstmodule.proxies.Test load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Test.initialize(context, mendixObject);
	}

	/**
	 * @return value of Pattern
	 */
	public final java.lang.String getPattern()
	{
		return getPattern(getContext());
	}

	/**
	 * @param context
	 * @return value of Pattern
	 */
	public final java.lang.String getPattern(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Pattern.toString());
	}

	/**
	 * Set value of Pattern
	 * @param pattern
	 */
	public final void setPattern(java.lang.String pattern)
	{
		setPattern(getContext(), pattern);
	}

	/**
	 * Set value of Pattern
	 * @param context
	 * @param pattern
	 */
	public final void setPattern(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pattern)
	{
		getMendixObject().setValue(context, MemberNames.Pattern.toString(), pattern);
	}

	/**
	 * @return value of RandomString
	 */
	public final java.lang.String getRandomString()
	{
		return getRandomString(getContext());
	}

	/**
	 * @param context
	 * @return value of RandomString
	 */
	public final java.lang.String getRandomString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RandomString.toString());
	}

	/**
	 * Set value of RandomString
	 * @param randomstring
	 */
	public final void setRandomString(java.lang.String randomstring)
	{
		setRandomString(getContext(), randomstring);
	}

	/**
	 * Set value of RandomString
	 * @param context
	 * @param randomstring
	 */
	public final void setRandomString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String randomstring)
	{
		getMendixObject().setValue(context, MemberNames.RandomString.toString(), randomstring);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Test that = (myfirstmodule.proxies.Test) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
